import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const quizAttemptSchema = new mongoose.Schema({
  quizId: { type: mongoose.Schema.Types.ObjectId, ref: 'Quiz' },
  courseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Course' },
  score: Number,
  totalQuestions: Number,
  wrongTopics: [String],
  completedAt: { type: Date, default: Date.now },
});

const enrollmentSchema = new mongoose.Schema({
  courseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Course' },
  enrolledAt: { type: Date, default: Date.now },
  completedLessons: [{ type: mongoose.Schema.Types.ObjectId }],
  progress: { type: Number, default: 0 },
  lastAccessed: Date,
});

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true },
    password: { type: String, minlength: 6 },
    avatar: { type: String, default: '' },
    role: { type: String, enum: ['student', 'instructor', 'admin'], default: 'student' },

    // AI Personalization
    learningStyle: { type: String, enum: ['visual', 'reading', 'kinesthetic', 'mixed'], default: 'mixed' },
    weakTopics: [String],
    strongTopics: [String],
    preferredDifficulty: { type: String, enum: ['beginner', 'intermediate', 'advanced'], default: 'beginner' },

    // Progress
    enrolledCourses: [enrollmentSchema],
    quizHistory: [quizAttemptSchema],

    // Study plan generated by AI
    studyPlan: [
      {
        topic: String,
        dueDate: Date,
        status: { type: String, enum: ['pending', 'done', 'skipped'], default: 'pending' },
        courseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Course' },
      },
    ],

    // Stripe
    stripeCustomerId: String,
    purchasedCourses: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Course' }],

    // OAuth
    googleId: String,
    isEmailVerified: { type: Boolean, default: false },

    resetPasswordToken: String,
    resetPasswordExpires: Date,
  },
  { timestamps: true }
);

// Hash password before save
userSchema.pre('save', async function (next) {
  if (!this.isModified('password') || !this.password) return next();
  this.password = await bcrypt.hash(this.password, 12);
  next();
});

userSchema.methods.comparePassword = async function (candidate) {
  return bcrypt.compare(candidate, this.password);
};

userSchema.methods.toPublicJSON = function () {
  const obj = this.toObject();
  delete obj.password;
  delete obj.resetPasswordToken;
  delete obj.resetPasswordExpires;
  return obj;
};

export default mongoose.model('User', userSchema);
